name: s3-test

services:

  s3-minio:
    container_name: s3-minio
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - s3-test
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "Pass@word1"
    volumes:
        - ./data/minio:/data
    command: server /data --console-address ":9001" 
      
networks:
  s3-test:
    driver: bridge